[package]
name = "USDTRepo"
version = "0.1.0"

[addresses]
UsdtIssuer = "0xee1f1439e9423f2c537e775d4cb92ea2cacdf0886165b7945db8262702c07049"
move_std = "0x1"
aptos_framework = "0x1"
aptos_std = "0x1"
aptos_token = "0x3"

[dependencies]
#StarcoinFramework = { git = "https://github.com/starcoinorg/starcoin-framework.git", rev = "01c84198819310620f2417413c3c800df8292ae5" }
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "02e41b3eb12df24103412630d20d72db8bcca2ed", subdir = "aptos-move/framework/aptos-framework"}
AptosStdlib = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "02e41b3eb12df24103412630d20d72db8bcca2ed", subdir = "aptos-move/framework/aptos-stdlib"}
MoveStdlib = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "02e41b3eb12df24103412630d20d72db8bcca2ed", subdir = "aptos-move/framework/move-stdlib"}
