[package]
name = "Starswap-Core"
version = "1.0.9"

[addresses]
StarcoinFramework = "0x1"
SwapAdmin = "0x8c109349c6bd91411d6bc962e080c4a3"
SwapFeeAdmin = "0x9572abb16f9d9e9b009cc1751727129e"

[dependencies]
StarcoinFramework = { git = "https://github.com/starcoinorg/starcoin-framework.git", rev = "8b60212bba9f1e49f345f21ff6cf7bbbe01e8fb1" }
Bridge = {local = "./bridge-dep"}