[package]
name = "Starswap-Core"
version = "1.0.12"

[addresses]
StarcoinFramework = "0x1"
SwapAdmin = "0x8c109349c6bd91411d6bc962e080c4a3"
SwapFeeAdmin = "0x9572abb16f9d9e9b009cc1751727129e"
BuyBackAccount = "0xa1869437e19a33eba1b7277218af539c"

[dependencies]
StarcoinFramework = { git = "https://github.com/starcoinorg/starcoin-framework.git", rev = "e82c1d32c98170e82f2145bf5a03badf8af06de7" }
Poly-STC-Bridge = { git = "https://github.com/Elements-Studio/poly-stc-contracts.git", rev = "3b2aea9a611b37fd21200cda6bde748e012908e6" }