[package]
name = "bridge-mock"
version = "1.0.0"

[addresses]
bridge = "0xe5db6a747cc2ba06bfd613c8eb2c4ded40a0d0f35e079e6a2961637901b7b7f6"
move_std = "0x1"
aptos_framework = "0x1"
aptos_std = "0x1"
aptos_token = "0x3"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "01108a2345b87d539d54a67b32db55193f9ace40", subdir = "aptos-move/framework/aptos-framework"}
