[package]
name = "U256"
version = "0.3.7"

[addresses]
u256 = "0xcf4da8647de3c41e95be5b2a5443001199abca760f717bbe9ee98d7d28c77553"

[dev-dependencies.MoveStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "02e41b3eb12df24103412630d20d72db8bcca2ed"
subdir = "aptos-move/framework/move-stdlib"
addr_subst = { std = "0x1" }

