[package]
name = "U256"
version = "0.3.7"

[addresses]
u256 = "0x0c3dbe4f07390f05b19ccfc083fc6aa5bc5d75621d131fc49557c8f4bbc11716"

[dev-dependencies.MoveStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "02e41b3eb12df24103412630d20d72db8bcca2ed"
subdir = "aptos-move/framework/move-stdlib"
addr_subst = { std = "0x1" }

