name: Build and Test
on:
  pull_request:
    branches:
      - master

jobs:
  starcoin-build-and-test:
    name: Starcoin build and test
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: checkout-move
        uses: actions/checkout@v3

      - name: setup environment
        run: |
          bash starcoin/scripts/dev_setup.sh -b -t -p

      - name: starcoin unittest
        run: |
          source "$HOME/.profile"
          mpm package test -p starcoin

      - name: starcoin integration test
        run: |
          source "$HOME/.profile"
          mpm integration-test -p starcoin

      - name: build
        run: |
          source "$HOME/.profile"
          mpm package build -p starcoin

      - name: check changed files
        run: bash ./starcoin/scripts/changed_files.sh

  aptos-build-and-test:
    name: Aptos build and test
    runs-on: ubuntu-22.04
    timeout-minutes: 20
    steps:
      - name: checkout-move
        uses: actions/checkout@v3

      - name: download and install aptos CI
        run: |
          bash aptos/scripts/dev_setup.sh -b -t -p

      - name: aptos swap core build and test
        run: |
          bash aptos/core/scripts/build.sh

#       - name: check aptos swap core changed files
#         run: bash ./aptos/core/scripts/changed_files.sh

#       - name: aptos swap farming build and test
#         run: |
#           source "$HOME/.profile"
#           bash aptos/farming/script/build.sh

#       - name: check aptos farming core changed files
#         run: bash ./aptos/farming/scripts/changed_files.sh
