name: Build and Test
on:
  pull_request:
    branches:
      - master

jobs:
  starcoin-build-and-test:
    name: build and test
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:     
      - name: checkout-move
        uses: actions/checkout@v3

      - name: setup environment
        run: |
          bash starcoin/scripts/dev_setup.sh -b -t -p 

      - name: test
        run: |
          source "$HOME/.profile"
          mpm package test -p starcoin

      - name: integration test
        run: |
          source "$HOME/.profile"
          mpm integration-test -p starcoin
          
      - name: build
        run: |
          source "$HOME/.profile"
          mpm package build -p starcoin

      - name: check changed files
        run: bash ./starcoin/scripts/changed_files.sh
